// !!        WARNING
// !! DO NOT EDIT THIS FILE
//
// This file is generated by the openapi-generator module and is not meant for manual changes.
// Please read the README.md file in the openapi-generator module for additional information.
@file:UseSerializers(UUIDSerializer::class)

package org.jellyfin.sdk.model.api

import kotlin.Int
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.UseSerializers
import org.jellyfin.sdk.model.UUID
import org.jellyfin.sdk.model.serializer.UUIDSerializer

/**
 * Api model for MediaSegment's.
 */
@Serializable
public data class MediaSegmentModel(
	/**
	 * The id of the media segment.
	 */
	@SerialName("Id")
	public val id: UUID,
	/**
	 * The id of the associated item.
	 */
	@SerialName("ItemId")
	public val itemId: UUID,
	/**
	 * The start of the segment.
	 */
	@SerialName("StartTick")
	public val startTick: Int,
	/**
	 * The end of the segment.
	 */
	@SerialName("EndTick")
	public val endTick: Int,
	/**
	 * The Type of content this segment defines.
	 */
	@SerialName("Type")
	public val type: MediaSegmentTypeModel,
)
